### ISSUE TITLE
How to remove google chrome?

### ISSUE THREAD

**Issue by DaviMenezes** [rafaelstz/simplesh#28]
Quero remover o chrome, como fazer?

**Comment by rafaelstz** [comment]
Remove Chrome

```bash
    sudo apt-get remove google-chrome-stable
```

**Comment by DaviMenezes** [comment]
Obrigado Rafael,  como fazer para incluir programas na lista?

**Comment by rafaelstz** [comment]
Se for uma instalação Desktop vai ser na pasta **desktop** em seguida add o script **meuappinstall.sh** na pasta e importa ele no arquivo **desktop/import.sh**
