### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by rafaelstz** [rafaelstz/simplesh#46]
New layout and code

**Comment by surendharreddy** [comment]
Can you elaborate it? What is that you are exactly looking for?

**Comment by KayvanMazaheri** [comment]
I want to work on this, do you have anything specific in mind?

**Comment by rafaelstz** [comment]
@KayvanMazaheri Nothing, but the actual website is very poor and ugly. 😞

**Comment by surendharreddy** [comment]
I'll also try to find some time for it over the weekend. Put in some references which are similar to your thoughts, so that it'll be easier for us to start.

@KayvanMazaheri What say?

**Comment by KayvanMazaheri** [comment]
Created a PR here #60 
What do you think about it guys? @rafaelstz @surendharreddy

**Comment by rafaelstz** [comment]
Great :+1: :smile:

**Comment by rafaelstz** [comment]
@surendharreddy feel free if you want to send suggestions in @KayvanMazaheri website!

**Comment by surendharreddy** [comment]
@rafaelstz  @KayvanMazaheri website looks great! I think we can go with it. 💯

**Comment by rafaelstz** [comment]
Great guys thanks! :smile:
