### ISSUE TITLE
Review README

### ISSUE THREAD

**Issue by rafaelstz** [rafaelstz/simplesh#48]

**Comment by mensonones** [comment]
Teu README está bom!

**Comment by nitinprakash96** [comment]
Dropbox section is missing in README

**Comment by michaelmior** [comment]
See #50 for some changes

**Comment by mensonones** [comment]
I made a pull request to the description of Dropbox in the README.

**Comment by Tocive** [comment]
I made two pull requests, one correcting readme.md (although there might be some errors still in there, I'm not perfect), and another making a tiny correction to simple.sh in master

**Comment by rafaelstz** [comment]
Thanks guys! 🎉  😄

**Comment by salman-bhai** [comment]
Hey, is this issue still open?

**Comment by rafaelstz** [comment]
@salman-bhai , yes if you have more suggestions,  please send me!

**Comment by salman-bhai** [comment]
I think you should close this Issue. The README can't be more perfect than this.
