### ISSUE TITLE
Install spotify

### ISSUE THREAD

**Issue by rafa-acioly** [rafaelstz/simplesh#55]
Tentei instalar o Spotify e recebi o erro;

```
W: Erro GPG: http://repository.spotify.com stable InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 13B00F1FD2C19886
W: The repository 'http://repository.spotify.com stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Este erro aparece quando rodo `apt-get update`, como posso arrumar isso?

**Comment by nitinprakash96** [comment]
Try this:
Open `Software & Updates`, at `Ubuntu Software tab` uncheck `Cdrom with Ubuntu 16.04 LTS 'Xenial Xerus'` under the section `Installable from CD-ROM/DVD`.

**Comment by rafa-acioly** [comment]
@nitinprakash96 i'm using 16.04.

**Comment by rafa-acioly** [comment]
I solved the problem by removing `spotify.list` files and` spotify.save` of
`/ Etc / apt / source / sources.list.d /`
and reinstalling again
